Task 18
Naive Bayes Classifier

In [61]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
from sklearn.naive_bayes import ComplementNB 
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

In [62]:
dataset=pd.read_csv('DATASET.csv',names=['Age','Sex','Chest Pain Location','Blood Pressure','Cholestoral','Fasting Blood Sugar','ResTecg','Thalach',' Exang','OldPeak','Diagnosis Heart Disease'])
dataset.head()

Age  Sex  Chest Pain Location  Blood Pressure  Cholestoral  \
0   40    1                    2             140          289   
1   49    0                    3             160          180   
2   37    1                    2             130          283   
3   48    0                    4             138          214   
4   54    1                    3             150            6   

   Fasting Blood Sugar  ResTecg  Thalach   Exang  OldPeak  \
0                    0        0      172       0      0.0   
1                    0        0      156       0      1.0   
2                    0        1       98       0      0.0   
3                    0        0      108       1      1.5   
4                    0        0      122       0      0.0   

   Diagnosis Heart Disease  
0                        0  
1                        1  
2                        0  
3                        3  
4                        0

In [63]:
# splitting the dataset
#  test_size=0.2 20% data is given to testing while 80% to training

x = dataset.iloc[:,0:-1]
y = dataset.iloc[: , -1]
x_train , x_test, y_train, y_test = train_test_split(x,y ,random_state=40, test_size=0.2)

In [64]:
# Train the Guassian Model
model = GaussianNB()
fittedModel = model.fit(x_train, y_train)

In [65]:
y_gnb = model.predict(x_test)
y_gnb

array([4, 0, 2, 0, 4, 0, 2, 2, 1, 0, 0, 2, 4, 4, 3, 0, 4, 0, 2, 2, 0, 0,
       4, 0, 0, 2, 2, 0, 0, 2, 1, 2, 4, 2, 0, 4, 2, 0, 2, 2, 2, 0, 0, 2,
       2, 0, 0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 0], dtype=int64)

In [66]:
print(accuracy_score(y_test,y_gnb))

0.4745762711864407


In [67]:
# Train the ComplementNB Model
model2 = ComplementNB()
fittedModel = model2.fit(x_train, y_train)
y_cnb = model2.predict(x_test)
y_cnb


array([2, 0, 1, 0, 2, 0, 3, 3, 0, 2, 1, 0, 0, 2, 3, 0, 2, 0, 0, 0, 1, 2,
       2, 0, 2, 0, 2, 1, 1, 2, 1, 3, 3, 0, 0, 3, 0, 0, 1, 0, 1, 0, 2, 3,
       2, 0, 0, 1, 1, 0, 1, 0, 2, 0, 0, 0, 1, 0, 0], dtype=int64)

In [68]:
print(accuracy_score(y_test,y_cnb))

0.423728813559322


In [69]:
# Train the Multinomial Model
model3 = MultinomialNB()
fittedModel = model3.fit(x_train, y_train)
y_mnb = model3.predict(x_test)
y_mnb


array([4, 0, 1, 0, 0, 0, 3, 3, 0, 4, 1, 0, 0, 4, 3, 1, 1, 0, 0, 0, 4, 2,
       4, 0, 0, 0, 2, 1, 1, 3, 1, 3, 3, 0, 0, 3, 0, 0, 4, 0, 4, 0, 2, 3,
       2, 0, 0, 4, 1, 0, 1, 1, 2, 0, 0, 0, 4, 1, 0], dtype=int64)

In [70]:
print(accuracy_score(y_test,y_mnb))

0.5084745762711864


In [71]:
# Train the BernoulliNB Model
model4 = BernoulliNB()
fittedModel = model4.fit(x_train, y_train)
y_bnb = model4.predict(x_test)
y_bnb


array([2, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 2, 1, 3, 2, 0, 2, 0, 2, 0, 0, 0,
       3, 0, 0, 0, 0, 0, 0, 2, 0, 3, 1, 0, 0, 2, 2, 0, 0, 2, 0, 0, 0, 0,
       2, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0], dtype=int64)

In [72]:
print(accuracy_score(y_test,y_bnb))

0.6271186440677966
